import { ThemeProvider, AppLayout } from "ui";
import { Nunito } from "next/font/google";
import { BreadcrumbProvider } from "hooks";
import type { Metadata } from "next";
import "./styles.css";

// Carrega a fonte Nunito com pesos 400, 600, 700
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Adicione os pesos que deseja
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${nunito.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <BreadcrumbProvider>
            <AppLayout> {children}</AppLayout>
          </BreadcrumbProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
